sudo: required
language: generic
services:
  - docker
script:
  - docker-compose build
after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
  - export REPO=cwac/hubot-slack-localz
  - export TAG=${TRAVIS_BRANCH//'/'/-}
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
after_script:
  - sh ecs-deploy.sh -c default -n hubot -i cwac/hubot-slack-localz --region eu-west-1